import AttachmentOpen
import Mathlib.Analysis.Convex.Contractible

open Function Set Topology
open scoped ContinuousMap unitInterval

noncomputable section

namespace PoincareConjecture

instance sphere2_pathConnected : PathConnectedSpace Sphere2 := by
  apply isPathConnected_iff_pathConnectedSpace.mp
  apply isPathConnected_sphere _ (0 : BallModel) zero_le_one
  rw [← Module.finrank_eq_rank, finrank_euclideanSpace_fin]
  exact_mod_cast (by norm_num : 1 < (3 : ℕ))

instance openThreeBall_contractible : ContractibleSpace OpenThreeBall :=
  (convex_ball (0 : BallModel) 1).contractibleSpace ⟨0, by simp⟩

abbrev RadialParameter := ↥(Ioo (0 : ℝ) 1)

instance radialParameter_pathConnected : PathConnectedSpace RadialParameter :=
  isPathConnected_iff_pathConnectedSpace.mp
    ((convex_Ioo (0 : ℝ) 1).isPathConnected ⟨1 / 2, by norm_num⟩)

variable {X : Type*} [TopologicalSpace X]

/-- Radial expansion joins every point of the punctured attachment to its
retained retraction point; paths in the retained side then join any pair. -/
theorem puncturedAttachment_pathConnected [PathConnectedSpace X] (i : C(Sphere2, X)) :
    PathConnectedSpace (PuncturedBallAttachment i) := by
  refine ⟨Nonempty.map (puncturedAttachmentInl i) inferInstance, ?_⟩
  intro q r
  let H := puncturedAttachmentDeformation i
  let middle := (PathConnectedSpace.somePath
    (puncturedAttachmentRetraction i q) (puncturedAttachmentRetraction i r)).map
      (puncturedAttachmentInl i).continuous
  exact ⟨((H.evalAt q).trans middle).trans (H.evalAt r).symm⟩

theorem ballAttachmentRetainedOpen_pathConnected [PathConnectedSpace X] (i : C(Sphere2, X)) :
    IsPathConnected (ballAttachmentRetainedOpen i) := by
  letI := puncturedAttachment_pathConnected i
  haveI := (puncturedAttachmentHomeomorph i).surjective.pathConnectedSpace
    (puncturedAttachmentHomeomorph i).continuous
  exact isPathConnected_iff_pathConnectedSpace.mpr inferInstance

theorem ballAttachmentCapOpen_simplyConnected [NormalSpace X]
    (i : C(Sphere2, X)) (hi : IsClosedEmbedding i) :
    IsSimplyConnected (ballAttachmentCapOpen i) :=
  (ballAttachmentCapHomeomorph i hi).toHomotopyEquiv.simplyConnectedSpace

/-- The overlap is generated by actual vectors `r • s`, with `s` on the
two-sphere and `0 < r < 1`. No annular chart or collar is postulated. -/
def capOverlapParametrization (i : C(Sphere2, X)) :
    C(Sphere2 × RadialParameter, BallAttachment i) := by
  have hnorm (p : Sphere2 × RadialParameter) :
      ‖(p.2 : ℝ) • (p.1 : BallModel)‖ = (p.2 : ℝ) := by
    rw [norm_smul, Real.norm_eq_abs, abs_of_pos p.2.property.1,
      mem_sphere_zero_iff_norm.mp p.1.property, mul_one]
  let F : C(Sphere2 × RadialParameter, ThreeBall) :=
    ⟨fun p => ⟨(p.2 : ℝ) • (p.1 : BallModel),
      mem_closedBall_zero_iff.mpr ((hnorm p).trans_le p.2.property.2.le)⟩, by
      apply Continuous.subtype_mk
      exact (continuous_subtype_val.comp continuous_snd).smul
        (continuous_subtype_val.comp continuous_fst)⟩
  exact (ballAttachmentInr i).comp F

theorem capOverlapParametrization_range (i : C(Sphere2, X)) :
    Set.range (capOverlapParametrization i) =
      ballAttachmentRetainedOpen i ∩ ballAttachmentCapOpen i := by
  apply Set.Subset.antisymm
  · rintro q ⟨⟨s, r⟩, rfl⟩
    change 0 < ‖(r : ℝ) • (s : BallModel)‖ ∧ ‖(r : ℝ) • (s : BallModel)‖ < 1
    rw [norm_smul, Real.norm_eq_abs, abs_of_pos r.property.1,
      mem_sphere_zero_iff_norm.mp s.property, mul_one]
    exact r.property
  · intro q hq
    induction q using Quot.ind with
    | _ z =>
      cases z with
      | inl x => exact False.elim (lt_irrefl (1 : ℝ) hq.2)
      | inr b =>
        have hb0 : 0 < ‖(b : BallModel)‖ := hq.1
        have hb1 : ‖(b : BallModel)‖ < 1 := hq.2
        refine ⟨⟨puncturedBallDirection ⟨b, hb0⟩, ⟨‖(b : BallModel)‖, hb0, hb1⟩⟩, ?_⟩
        change ballAttachmentInr i _ = ballAttachmentInr i b
        congr 1
        apply Subtype.ext
        change ‖(b : BallModel)‖ • (‖(b : BallModel)‖⁻¹ • (b : BallModel)) = b
        rw [smul_smul, mul_inv_cancel₀ hb0.ne', one_smul]

theorem ballAttachment_overlap_pathConnected (i : C(Sphere2, X)) :
    IsPathConnected (ballAttachmentRetainedOpen i ∩ ballAttachmentCapOpen i) := by
  rw [← capOverlapParametrization_range i]
  exact isPathConnected_range (capOverlapParametrization i).continuous

/-- With a normal retained side and a closed embedded attaching sphere, the
actual ball attachment is path connected whenever the retained side is. -/
theorem ballAttachment_pathConnected [NormalSpace X] [PathConnectedSpace X]
    (i : C(Sphere2, X)) (hi : IsClosedEmbedding i) : PathConnectedSpace (BallAttachment i) := by
  have hu := ballAttachmentRetainedOpen_pathConnected i
  have hv := (ballAttachmentCapOpen_simplyConnected i hi).isPathConnected
  have huV := hu.union hv (ballAttachment_overlap_pathConnected i).nonempty
  rw [ballAttachment_opens_cover] at huV
  exact pathConnectedSpace_iff_univ.mpr huV

end PoincareConjecture
